import { Geist, Geist_Mono } from "next/font/google";
import { CookiesProvider } from 'next-client-cookies/server';
import "./globals.css";
import AppState from "./context/AppState";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "CCC | Login",
  description: "Generated by create next app",
};

export default function RootLayout({ children })
{
  return (
    <AppState>
      <CookiesProvider>
        <html lang="en">
          <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
          >
            {children}
          </body>
        </html>
      </CookiesProvider>
    </AppState>
  );
}
